# Generated by Django 5.2.8 on 2025-11-06 19:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('moisture_min', models.FloatField(help_text='Minimum moisture threshold (%)')),
                ('moisture_max', models.FloatField(help_text='Maximum moisture threshold (%)')),
                ('optimal_temp_min', models.FloatField(default=15.0, help_text='Minimum temperature (°C)')),
                ('optimal_temp_max', models.FloatField(default=35.0, help_text='Maximum temperature (°C)')),
                ('optimal_humidity_min', models.FloatField(default=40.0, help_text='Minimum humidity (%)')),
                ('optimal_humidity_max', models.FloatField(default=80.0, help_text='Maximum humidity (%)')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='disease_images/')),
                ('predicted_disease', models.CharField(max_length=200)),
                ('confidence', models.FloatField()),
                ('remedy', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='ESP32_001', max_length=50)),
                ('moisture', models.FloatField(help_text='Soil moisture level (%)')),
                ('temperature', models.FloatField(help_text='Temperature (°C)')),
                ('humidity', models.FloatField(help_text='Air humidity (%)')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Sensor Data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ActiveCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartcare.crop')),
            ],
            options={
                'ordering': ['-activated_at'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay_state', models.BooleanField(help_text='True=ON, False=OFF')),
                ('reason', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartcare.crop')),
                ('sensor_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartcare.sensordata')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
